store_data: /opt/go-wrapper-ffmpeg-rtsp-to-mp4/data
cameras:
  - name: camera-01
    server: rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen03.stream
  - name: camera-02
    server: rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen03.stream
